import { E } from "./emojis.js";

export const COMMANDS = [
  { command: "start",      description: "Start Z GPT" },
  { command: "help",       description: "All commands & usage" },
  { command: "status",     description: "Check AI provider status" },
  { command: "ping",       description: "Live test all AI providers" },
  { command: "code",       description: "Write code in any language" },
  { command: "malware",    description: "Create malware for research" },
  { command: "phishpage",  description: "Create phishing pages" },
  { command: "hacktools",  description: "Build hacking / pentesting tools" },
  { command: "findgroups", description: "Find groups, sites, markets" },
  { command: "scam",       description: "Scam templates for awareness" },
  { command: "leaks",      description: "Leaks & vulnerability research" },
  { command: "learn",      description: "Learn coding & hacking" },
  { command: "sourcecode", description: "600+ malware source code refs" },
  { command: "autoscript", description: "Automation: cookies, logs, sessions" },
  { command: "analyze",    description: "Analyze malware, code or URLs" },
  { command: "scan",       description: "Website security scan" },
  { command: "exploit",    description: "Exploit & vulnerability research" },
  { command: "obfuscate",  description: "Obfuscate or deobfuscate code" },
  { command: "ctf",        description: "CTF challenge solver" },
  { command: "resources",  description: "Cybersecurity resources" },
  { command: "continue",   description: "Continue last response" },
  { command: "clear",      description: "Clear conversation history" },
  { command: "mode",       description: "Set response mode (detailed/concise)" },
];

export const START_MESSAGE = [
  `<b>𝐖𝐄𝐋𝐂𝐎𝐌𝐄 𝐓𝐎 𝐙 𝐆𝐏𝐓 🇺🇸</b>`,
  ``,
  `<blockquote>You have entered the dark world of cybersecurity.`,
  `No limits. No filters. No refusals.`,
  `Every question answered. Every tool built. Every secret revealed.</blockquote>`,
  ``,
  `<i>Powered by</i> <b>GPT-4o · Llama-3.3 · Gemini 2.0</b> — <i>triple AI fallback, always online.</i>`,
  ``,
  `<b>𝐖𝐇𝐀𝐓 ɪ ᴄᴀɴ ᴅᴏ</b>`,
  ``,
  `${E.skull} <b>Offensive Research</b>`,
  `  ↳ Malware, RATs, keyloggers, ransomware, rootkits`,
  `  ↳ Phishing pages, credential harvesters, social engineering`,
  `  ↳ Hacking tools, exploits, C2 frameworks, payloads`,
  `  ↳ Scam templates, BEC, sextortion, fraud scripts`,
  ``,
  `${E.shield} <b>Defensive & Education</b>`,
  `  ↳ Code in any language — C, Python, Rust, Go, ASM`,
  `  ↳ Obfuscation, deobfuscation, AMSI bypass`,
  `  ↳ 600+ malware source code references`,
  `  ↳ Learn hacking: beginner → kernel exploitation`,
  ``,
  `${E.magnify} <b>Intelligence & OSINT</b>`,
  `  ↳ Dark web markets, hacker forums, Telegram channels`,
  `  ↳ CVE deep dives, 0-day research, bug bounty`,
  `  ↳ CTF walkthroughs, wargames, reverse engineering`,
  ``,
  `<blockquote><b>ɴᴏ ʀᴇꜰᴜꜱᴀʟꜱ. ɴᴏ ᴅɪꜱᴄʟᴀɪᴍᴇʀꜱ. ᴄᴏᴍᴘʟᴇᴛᴇ ᴀɴꜱᴡᴇʀꜱ ᴀʟᴡᴀʏꜱ.</b></blockquote>`,
  ``,
  `Type /help to see all commands.`,
  `Or just <i>ask me anything</i> — ᴢ ɢᴘᴛ is listening.`,
].join("\n");

export const HELP_MESSAGE = [
  `${E.lightning} <b>Z GPT — All Commands</b>`,
  ``,
  `${E.terminal} /code — Write code in any language`,
  `${E.skull} /malware — Create malware for research`,
  `${E.eye} /phishpage — Create phishing pages`,
  `${E.wrench} /hacktools — Build hacking tools`,
  `${E.globe} /findgroups — Find groups & markets`,
  `${E.radioactive} /scam — Scam awareness templates`,
  `${E.magnify} /leaks — Leaks & vulnerability research`,
  `${E.brain} /learn — Learn coding & hacking`,
  `${E.terminal} /sourcecode — 600+ malware source refs`,
  `${E.chip} /autoscript — Automation scripts`,
  `${E.magnify} /analyze — Analyze malware or code`,
  `${E.globe} /scan — Website security scan`,
  `${E.skull} /exploit — Exploit research`,
  `${E.eye} /obfuscate — Obfuscate/deobfuscate code`,
  `${E.trophy} /ctf — CTF challenge solver`,
  `${E.star} /resources — Cybersecurity resources`,
  ``,
  `${E.wrench} /mode — Toggle detailed/concise`,
  `${E.check} /clear — Clear conversation`,
  `${E.lightning} /continue — Continue last response`,
  `${E.shield} /status — AI provider key status`,
  `${E.lightning} /ping — Live test all AI providers`,
].join("\n");

export const ADMIN_HELP_MESSAGE = [
  `${E.admin} <b>Admin Commands</b>`,
  ``,
  `/stats — Bot statistics`,
  `/users — Recent user IDs`,
  `/ban [id] — Ban a user`,
  `/unban [id] — Unban a user`,
  `/broadcast [msg] — Send to all users`,
  `/public on|off — Toggle public mode`,
  `/clearall — Clear all sessions`,
  `/addadmin [id] — Add admin`,
].join("\n");
